version:  "3.9"

services:

  webserver-driver:
    image: nginx:alpine
    container_name: projeto3-driver-nginx
    working_dir: /app
    restart: unless-stopped
    volumes:
        - ./:/app
        - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 8888:80
    networks:
        - projeto3-network

  php-fpm-api:
    build: .docker/php-fpm
    container_name: projeto3-php8
    restart: unless-stopped
    working_dir: /app
    expose:
        - 9000
    volumes:
        - ./:/app
    networks:
        - projeto3-network

  redis:
    image: redis:7.0-alpine
    container_name: projeto3-redis
    restart: always
    env_file:
        - .env
    command: redis-server --save 20 1 --loglevel warning --requirepass guest
    ports:
        - 6379:6379
    volumes:
        - ./.docker-conf/redis-data:/data
    networks:
        - projeto3-network

  db:
    image: postgres
    restart: always
    container_name: projeto3-db
    volumes:
        - data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
        - projeto3-network
    environment:
      POSTGRES_PASSWORD: "4B:s5geAe367sl8787?Z~Mj!"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
networks:
  projeto3-network:
    name: 'projeto3-network'
volumes:
  data: {}
